import type {
  ComponentBlueprint,
  ComponentBlueprintAttribute,
  ComponentBlueprintStyleHook,
  ComponentStyleTarget
} from '../blueprint/component-blueprint.js';
import { componentBlueprints } from '../blueprint/components/index.js';

export const GENERATED_COMPONENT_DIRECTORY = 'src/generated/components';

export interface GeneratedComponentArtifact {
  componentId: string;
  tagName: string;
  artifactFileName: string;
  source: string;
}

interface StyleTargetSelector {
  selector: string;
  target: ComponentStyleTarget;
}

const FILE_HEADER_LINES = [
  '// This file is generated by @prism/ui-core component blueprints.',
  '// Do not edit this file manually.',
  ''
];

function findAttribute(blueprint: ComponentBlueprint, attributeName: string): ComponentBlueprintAttribute {
  const attribute = blueprint.attributes.find((entry) => entry.name === attributeName);

  if (!attribute) {
    throw new Error(`Missing attribute "${attributeName}" on component blueprint "${blueprint.componentId}".`);
  }

  return attribute;
}

function enumValues(attribute: ComponentBlueprintAttribute): readonly string[] {
  if (attribute.type !== 'enum' || !attribute.enumValues || attribute.enumValues.length === 0) {
    throw new Error(`Attribute "${attribute.name}" must define enumValues.`);
  }

  return attribute.enumValues;
}

function enumDefault(attribute: ComponentBlueprintAttribute): string {
  if (attribute.type !== 'enum' || typeof attribute.defaultValue !== 'string') {
    throw new Error(`Attribute "${attribute.name}" must define a string defaultValue.`);
  }

  return attribute.defaultValue;
}

function renderArray(values: readonly string[]): string {
  return `[${values.map((value) => JSON.stringify(value)).join(', ')}]`;
}

function hookDeclaration(hook: ComponentBlueprintStyleHook): string {
  const fallback = hook.fallback ? `, ${hook.fallback}` : '';
  return `  ${hook.cssProperty}: var(${hook.cssVariable}${fallback});`;
}

function renderStyleHooks(
  blueprint: ComponentBlueprint,
  selectorMap: readonly StyleTargetSelector[]
): string {
  const blocks = selectorMap
    .map(({ selector, target }) => {
      const hooks = blueprint.styleHooks
        .filter((entry) => entry.target === target)
        .sort((left, right) => left.name.localeCompare(right.name));

      if (hooks.length === 0) {
        return '';
      }

      return [selector + ' {', ...hooks.map((hook) => hookDeclaration(hook)), '}'].join('\n');
    })
    .filter((entry) => entry.length > 0);

  return blocks.join('\n\n');
}

function buttonSource(blueprint: ComponentBlueprint): string {
  const variantAttribute = findAttribute(blueprint, 'variant');
  const sizeAttribute = findAttribute(blueprint, 'size');
  const typeAttribute = findAttribute(blueprint, 'type');

  const variants = enumValues(variantAttribute);
  const sizes = enumValues(sizeAttribute);
  const types = enumValues(typeAttribute);

  const defaultVariant = enumDefault(variantAttribute);
  const defaultSize = enumDefault(sizeAttribute);
  const defaultType = enumDefault(typeAttribute);

  const styleHooks = renderStyleHooks(blueprint, [
    { selector: ':host', target: 'host' },
    { selector: '.container', target: 'container' },
    { selector: '.control', target: 'control' },
    { selector: '.label', target: 'text' },
    { selector: '.icon-slot', target: 'icon' }
  ]);

  return [
    ...FILE_HEADER_LINES,
    'const PrismHTMLElement = globalThis.HTMLElement ?? class {};',
    `const BUTTON_VARIANTS = Object.freeze(${renderArray(variants)});`,
    `const BUTTON_SIZES = Object.freeze(${renderArray(sizes)});`,
    `const BUTTON_TYPES = Object.freeze(${renderArray(types)});`,
    `const DEFAULT_VARIANT = ${JSON.stringify(defaultVariant)};`,
    `const DEFAULT_SIZE = ${JSON.stringify(defaultSize)};`,
    `const DEFAULT_TYPE = ${JSON.stringify(defaultType)};`,
    '',
    `export const ${blueprint.className}Slots = Object.freeze(${renderArray(blueprint.slots.map((slot) => slot.name))});`,
    `export const ${blueprint.className}Parts = Object.freeze(${renderArray(blueprint.parts.map((part) => part.name))});`,
    '',
    `export class ${blueprint.className} extends PrismHTMLElement {`,
    `  static tagName = ${JSON.stringify(blueprint.tagName)};`,
    `  static observedAttributes = Object.freeze(${renderArray(
      blueprint.attributes.map((attribute) => attribute.name).sort((left, right) => left.localeCompare(right))
    )});`,
    '',
    '  #control = null;',
    '  #label = null;',
    '',
    '  constructor() {',
    '    super();',
    '    if (typeof this.attachShadow === "function" && !this.shadowRoot) {',
    '      this.attachShadow({ mode: "open" });',
    '    }',
    '  }',
    '',
    '  connectedCallback() {',
    '    this.#render();',
    '    this.#sync();',
    '  }',
    '',
    '  attributeChangedCallback() {',
    '    this.#sync();',
    '  }',
    '',
    '  #render() {',
    '    if (!this.shadowRoot || this.shadowRoot.childNodes.length > 0) {',
    '      return;',
    '    }',
    '',
    '    this.shadowRoot.innerHTML = `',
    '<style>',
    ':host {',
    '  display: inline-flex;',
    '  vertical-align: middle;',
    '}',
    '',
    '.container {',
    '  display: inline-flex;',
    '}',
    '',
    '.control {',
    '  align-items: center;',
    '  border: 1px solid transparent;',
    '  cursor: pointer;',
    '  display: inline-flex;',
    '  gap: 0.5rem;',
    '  justify-content: center;',
    '  min-height: 2.5rem;',
    '  min-width: 2.5rem;',
    '  padding-inline: 1rem;',
    '  transition: background-color 120ms ease, border-color 120ms ease, color 120ms ease;',
    '}',
    '',
    '.control:focus-visible {',
    '  outline: 2px solid var(--prism-color-outline, #74777f);',
    '  outline-offset: 2px;',
    '}',
    '',
    '.control:disabled {',
    '  cursor: not-allowed;',
    '  opacity: 0.38;',
    '}',
    '',
    '.icon-slot {',
    '  display: inline-flex;',
    '  line-height: 1;',
    '}',
    '',
    '.label {',
    '  display: inline-flex;',
    '  text-align: center;',
    '}',
    '',
    styleHooks,
    '</style>',
    '<span class="container" part="container">',
    '  <button class="control" part="control" type="button">',
    '    <span class="icon-slot" part="leading-icon"><slot name="leading"></slot></span>',
    '    <span class="label" part="label"><slot></slot></span>',
    '    <span class="icon-slot" part="trailing-icon"><slot name="trailing"></slot></span>',
    '  </button>',
    '</span>',
    '`;',
    '',
    '    this.#control = this.shadowRoot.querySelector(".control");',
    '    this.#label = this.shadowRoot.querySelector(".label");',
    '  }',
    '',
    '  #sync() {',
    '    const control = this.#control;',
    '    const label = this.#label;',
    '',
    '    if (!control || !label) {',
    '      return;',
    '    }',
    '',
    '    const variant = this.getAttribute("variant");',
    '    const size = this.getAttribute("size");',
    '    const type = this.getAttribute("type");',
    '',
    '    const resolvedVariant = BUTTON_VARIANTS.includes(variant ?? "") ? variant : DEFAULT_VARIANT;',
    '    const resolvedSize = BUTTON_SIZES.includes(size ?? "") ? size : DEFAULT_SIZE;',
    '    const resolvedType = BUTTON_TYPES.includes(type ?? "") ? type : DEFAULT_TYPE;',
    '',
    '    const variantStyles = {',
    '      filled: {',
    '        backgroundColor: "var(--prism-color-primary, #0057d9)",',
    '        borderColor: "transparent",',
    '        color: "var(--prism-color-on-primary, #ffffff)"',
    '      },',
    '      outlined: {',
    '        backgroundColor: "transparent",',
    '        borderColor: "var(--prism-color-outline, #74777f)",',
    '        color: "var(--prism-color-primary, #0057d9)"',
    '      },',
    '      tonal: {',
    '        backgroundColor: "var(--prism-color-secondary-container, #d6e3ff)",',
    '        borderColor: "transparent",',
    '        color: "var(--prism-color-on-secondary-container, #091b36)"',
    '      },',
    '      text: {',
    '        backgroundColor: "transparent",',
    '        borderColor: "transparent",',
    '        color: "var(--prism-color-primary, #0057d9)"',
    '      }',
    '    };',
    '',
    '    const sizeStyles = {',
    '      small: {',
    '        minHeight: "2rem",',
    '        paddingInline: "0.75rem",',
    '        typographySize: "small"',
    '      },',
    '      medium: {',
    '        minHeight: "2.5rem",',
    '        paddingInline: "1rem",',
    '        typographySize: "medium"',
    '      },',
    '      large: {',
    '        minHeight: "3rem",',
    '        paddingInline: "1.25rem",',
    '        typographySize: "large"',
    '      }',
    '    };',
    '',
    '    const variantStyle = variantStyles[resolvedVariant];',
    '    const sizeStyle = sizeStyles[resolvedSize];',
    '',
    '    control.type = resolvedType;',
    '    control.disabled = this.hasAttribute("disabled");',
    '    control.style.backgroundColor = variantStyle.backgroundColor;',
    '    control.style.borderColor = variantStyle.borderColor;',
    '    control.style.color = variantStyle.color;',
    '    control.style.minHeight = sizeStyle.minHeight;',
    '    control.style.paddingInline = sizeStyle.paddingInline;',
    '',
    '    label.style.fontFamily = `var(--prism-typography-label-${sizeStyle.typographySize}-font-family)`;',
    '    label.style.fontSize = `var(--prism-typography-label-${sizeStyle.typographySize}-font-size)`;',
    '    label.style.fontWeight = `var(--prism-typography-label-${sizeStyle.typographySize}-font-weight)`;',
    '    label.style.letterSpacing = `var(--prism-typography-label-${sizeStyle.typographySize}-letter-spacing)`;',
    '    label.style.lineHeight = `var(--prism-typography-label-${sizeStyle.typographySize}-line-height)`;',
    '  }',
    '}',
    '',
    `export function register${blueprint.className}() {`,
    '  if (typeof customElements === "undefined") {',
    '    return;',
    '  }',
    '',
    `  if (!customElements.get(${JSON.stringify(blueprint.tagName)})) {`,
    `    customElements.define(${JSON.stringify(blueprint.tagName)}, ${blueprint.className});`,
    '  }',
    '}',
    ''
  ].join('\n');
}

function iconButtonSource(blueprint: ComponentBlueprint): string {
  const variantAttribute = findAttribute(blueprint, 'variant');
  const sizeAttribute = findAttribute(blueprint, 'size');
  const typeAttribute = findAttribute(blueprint, 'type');

  const variants = enumValues(variantAttribute);
  const sizes = enumValues(sizeAttribute);
  const types = enumValues(typeAttribute);

  const defaultVariant = enumDefault(variantAttribute);
  const defaultSize = enumDefault(sizeAttribute);
  const defaultType = enumDefault(typeAttribute);

  const styleHooks = renderStyleHooks(blueprint, [
    { selector: ':host', target: 'host' },
    { selector: '.container', target: 'container' },
    { selector: '.control', target: 'control' },
    { selector: '.icon', target: 'icon' },
    { selector: '.assistive', target: 'text' }
  ]);

  return [
    ...FILE_HEADER_LINES,
    'const PrismHTMLElement = globalThis.HTMLElement ?? class {};',
    `const ICON_BUTTON_VARIANTS = Object.freeze(${renderArray(variants)});`,
    `const ICON_BUTTON_SIZES = Object.freeze(${renderArray(sizes)});`,
    `const ICON_BUTTON_TYPES = Object.freeze(${renderArray(types)});`,
    `const DEFAULT_VARIANT = ${JSON.stringify(defaultVariant)};`,
    `const DEFAULT_SIZE = ${JSON.stringify(defaultSize)};`,
    `const DEFAULT_TYPE = ${JSON.stringify(defaultType)};`,
    '',
    `export const ${blueprint.className}Slots = Object.freeze(${renderArray(blueprint.slots.map((slot) => slot.name))});`,
    `export const ${blueprint.className}Parts = Object.freeze(${renderArray(blueprint.parts.map((part) => part.name))});`,
    '',
    `export class ${blueprint.className} extends PrismHTMLElement {`,
    `  static tagName = ${JSON.stringify(blueprint.tagName)};`,
    `  static observedAttributes = Object.freeze(${renderArray(
      blueprint.attributes.map((attribute) => attribute.name).sort((left, right) => left.localeCompare(right))
    )});`,
    '',
    '  #control = null;',
    '  #icon = null;',
    '  #assistiveSlot = null;',
    '',
    '  constructor() {',
    '    super();',
    '    if (typeof this.attachShadow === "function" && !this.shadowRoot) {',
    '      this.attachShadow({ mode: "open" });',
    '    }',
    '  }',
    '',
    '  connectedCallback() {',
    '    this.#render();',
    '    this.#sync();',
    '  }',
    '',
    '  attributeChangedCallback() {',
    '    this.#sync();',
    '  }',
    '',
    '  #render() {',
    '    if (!this.shadowRoot || this.shadowRoot.childNodes.length > 0) {',
    '      return;',
    '    }',
    '',
    '    this.shadowRoot.innerHTML = `',
    '<style>',
    ':host {',
    '  display: inline-flex;',
    '  vertical-align: middle;',
    '}',
    '',
    '.container {',
    '  display: inline-flex;',
    '}',
    '',
    '.control {',
    '  align-items: center;',
    '  border: 1px solid transparent;',
    '  cursor: pointer;',
    '  display: inline-flex;',
    '  height: 2.5rem;',
    '  justify-content: center;',
    '  padding: 0;',
    '  transition: background-color 120ms ease, border-color 120ms ease, color 120ms ease;',
    '  width: 2.5rem;',
    '}',
    '',
    '.control:focus-visible {',
    '  outline: 2px solid var(--prism-color-outline, #74777f);',
    '  outline-offset: 2px;',
    '}',
    '',
    '.control:disabled {',
    '  cursor: not-allowed;',
    '  opacity: 0.38;',
    '}',
    '',
    '.icon {',
    '  display: inline-flex;',
    '  line-height: 1;',
    '}',
    '',
    '.assistive {',
    '  border: 0;',
    '  clip: rect(0 0 0 0);',
    '  clip-path: inset(50%);',
    '  height: 1px;',
    '  margin: -1px;',
    '  overflow: hidden;',
    '  padding: 0;',
    '  position: absolute;',
    '  white-space: nowrap;',
    '  width: 1px;',
    '}',
    '',
    ':host([data-a11y-issue="missing-aria-label"]) .control {',
    '  outline: 2px dashed var(--prism-color-error, #ba1a1a);',
    '  outline-offset: 2px;',
    '}',
    '',
    styleHooks,
    '</style>',
    '<span class="container" part="container">',
    '  <button class="control" part="control" type="button">',
    '    <span class="icon" part="icon"><slot name="icon"></slot></span>',
    '    <span class="assistive" part="assistive"><slot></slot></span>',
    '  </button>',
    '</span>',
    '`;',
    '',
    '    this.#control = this.shadowRoot.querySelector(".control");',
    '    this.#icon = this.shadowRoot.querySelector(".icon");',
    '    this.#assistiveSlot = this.shadowRoot.querySelector("slot:not([name])");',
    '    this.#assistiveSlot?.addEventListener("slotchange", () => this.#sync());',
    '  }',
    '',
    '  #assistiveText() {',
    '    if (!this.#assistiveSlot) {',
    '      return "";',
    '    }',
    '',
    '    return this.#assistiveSlot',
    '      .assignedNodes({ flatten: true })',
    '      .map((node) => node.textContent ?? "")',
    '      .join(" ")',
    '      .trim();',
    '  }',
    '',
    '  #sync() {',
    '    const control = this.#control;',
    '    const icon = this.#icon;',
    '',
    '    if (!control || !icon) {',
    '      return;',
    '    }',
    '',
    '    const variant = this.getAttribute("variant");',
    '    const size = this.getAttribute("size");',
    '    const type = this.getAttribute("type");',
    '',
    '    const resolvedVariant = ICON_BUTTON_VARIANTS.includes(variant ?? "") ? variant : DEFAULT_VARIANT;',
    '    const resolvedSize = ICON_BUTTON_SIZES.includes(size ?? "") ? size : DEFAULT_SIZE;',
    '    const resolvedType = ICON_BUTTON_TYPES.includes(type ?? "") ? type : DEFAULT_TYPE;',
    '',
    '    const variantStyles = {',
    '      filled: {',
    '        backgroundColor: "var(--prism-color-primary, #0057d9)",',
    '        borderColor: "transparent",',
    '        color: "var(--prism-color-on-primary, #ffffff)"',
    '      },',
    '      outlined: {',
    '        backgroundColor: "transparent",',
    '        borderColor: "var(--prism-color-outline, #74777f)",',
    '        color: "var(--prism-color-primary, #0057d9)"',
    '      },',
    '      tonal: {',
    '        backgroundColor: "var(--prism-color-secondary-container, #d6e3ff)",',
    '        borderColor: "transparent",',
    '        color: "var(--prism-color-on-secondary-container, #091b36)"',
    '      },',
    '      text: {',
    '        backgroundColor: "transparent",',
    '        borderColor: "transparent",',
    '        color: "var(--prism-color-primary, #0057d9)"',
    '      }',
    '    };',
    '',
    '    const sizeStyles = {',
    '      small: {',
    '        dimension: "2rem",',
    '        iconSize: "small"',
    '      },',
    '      medium: {',
    '        dimension: "2.5rem",',
    '        iconSize: "medium"',
    '      },',
    '      large: {',
    '        dimension: "3rem",',
    '        iconSize: "large"',
    '      }',
    '    };',
    '',
    '    const variantStyle = variantStyles[resolvedVariant];',
    '    const sizeStyle = sizeStyles[resolvedSize];',
    '',
    '    control.type = resolvedType;',
    '    control.disabled = this.hasAttribute("disabled");',
    '    control.style.backgroundColor = variantStyle.backgroundColor;',
    '    control.style.borderColor = variantStyle.borderColor;',
    '    control.style.color = variantStyle.color;',
    '    control.style.width = sizeStyle.dimension;',
    '    control.style.height = sizeStyle.dimension;',
    '    icon.style.fontSize = `var(--prism-typography-title-${sizeStyle.iconSize}-font-size)`;',
    '',
    '    const ariaLabel = this.getAttribute("aria-label")?.trim() ?? "";',
    '    const assistiveText = this.#assistiveText();',
    '    const accessibleName = ariaLabel.length > 0 ? ariaLabel : assistiveText;',
    '',
    '    if (accessibleName.length > 0) {',
    '      control.setAttribute("aria-label", accessibleName);',
    '      this.removeAttribute("data-a11y-issue");',
    '      return;',
    '    }',
    '',
    '    control.removeAttribute("aria-label");',
    '    this.setAttribute("data-a11y-issue", "missing-aria-label");',
    '  }',
    '}',
    '',
    `export function register${blueprint.className}() {`,
    '  if (typeof customElements === "undefined") {',
    '    return;',
    '  }',
    '',
    `  if (!customElements.get(${JSON.stringify(blueprint.tagName)})) {`,
    `    customElements.define(${JSON.stringify(blueprint.tagName)}, ${blueprint.className});`,
    '  }',
    '}',
    ''
  ].join('\n');
}

function typographySource(blueprint: ComponentBlueprint): string {
  const variantAttribute = findAttribute(blueprint, 'variant');
  const sizeAttribute = findAttribute(blueprint, 'size');
  const asAttribute = findAttribute(blueprint, 'as');

  const variants = enumValues(variantAttribute);
  const sizes = enumValues(sizeAttribute);
  const tagNames = enumValues(asAttribute);

  const defaultVariant = enumDefault(variantAttribute);
  const defaultSize = enumDefault(sizeAttribute);
  const defaultTagName = enumDefault(asAttribute);

  const styleHooks = renderStyleHooks(blueprint, [
    { selector: ':host', target: 'host' },
    { selector: '.container', target: 'container' },
    { selector: '.text', target: 'text' }
  ]);

  return [
    ...FILE_HEADER_LINES,
    'const PrismHTMLElement = globalThis.HTMLElement ?? class {};',
    `const TYPOGRAPHY_VARIANTS = Object.freeze(${renderArray(variants)});`,
    `const TYPOGRAPHY_SIZES = Object.freeze(${renderArray(sizes)});`,
    `const TYPOGRAPHY_TAG_NAMES = Object.freeze(${renderArray(tagNames)});`,
    `const DEFAULT_VARIANT = ${JSON.stringify(defaultVariant)};`,
    `const DEFAULT_SIZE = ${JSON.stringify(defaultSize)};`,
    `const DEFAULT_TAG_NAME = ${JSON.stringify(defaultTagName)};`,
    '',
    `export const ${blueprint.className}Slots = Object.freeze(${renderArray(blueprint.slots.map((slot) => slot.name))});`,
    `export const ${blueprint.className}Parts = Object.freeze(${renderArray(blueprint.parts.map((part) => part.name))});`,
    '',
    `export class ${blueprint.className} extends PrismHTMLElement {`,
    `  static tagName = ${JSON.stringify(blueprint.tagName)};`,
    `  static observedAttributes = Object.freeze(${renderArray(
      blueprint.attributes.map((attribute) => attribute.name).sort((left, right) => left.localeCompare(right))
    )});`,
    '',
    '  #text = null;',
    '  #textTagName = "";',
    '',
    '  constructor() {',
    '    super();',
    '    if (typeof this.attachShadow === "function" && !this.shadowRoot) {',
    '      this.attachShadow({ mode: "open" });',
    '    }',
    '  }',
    '',
    '  connectedCallback() {',
    '    this.#render();',
    '    this.#sync();',
    '  }',
    '',
    '  attributeChangedCallback() {',
    '    this.#sync();',
    '  }',
    '',
    '  #render() {',
    '    if (!this.shadowRoot || this.shadowRoot.childNodes.length > 0) {',
    '      return;',
    '    }',
    '',
    '    this.shadowRoot.innerHTML = `',
    '<style>',
    ':host {',
    '  display: block;',
    '}',
    '',
    '.container {',
    '  display: contents;',
    '}',
    '',
    '.text {',
    '  margin: 0;',
    '}',
    '',
    styleHooks,
    '</style>',
    '<span class="container"></span>',
    '`;',
    '  }',
    '',
    '  #ensureText(tagName) {',
    '    if (!this.shadowRoot || typeof document === "undefined") {',
    '      return null;',
    '    }',
    '',
    '    const container = this.shadowRoot.querySelector(".container");',
    '    if (!container) {',
    '      return null;',
    '    }',
    '',
    '    if (this.#text && this.#textTagName === tagName) {',
    '      return this.#text;',
    '    }',
    '',
    '    const text = document.createElement(tagName);',
    '    text.className = "text";',
    '    text.setAttribute("part", "text");',
    '    text.innerHTML = "<slot></slot>";',
    '    container.replaceChildren(text);',
    '',
    '    this.#text = text;',
    '    this.#textTagName = tagName;',
    '    return text;',
    '  }',
    '',
    '  #sync() {',
    '    const variant = this.getAttribute("variant");',
    '    const size = this.getAttribute("size");',
    '    const as = this.getAttribute("as");',
    '',
    '    const resolvedVariant = TYPOGRAPHY_VARIANTS.includes(variant ?? "") ? variant : DEFAULT_VARIANT;',
    '    const resolvedSize = TYPOGRAPHY_SIZES.includes(size ?? "") ? size : DEFAULT_SIZE;',
    '    const resolvedTagName = TYPOGRAPHY_TAG_NAMES.includes(as ?? "") ? as : DEFAULT_TAG_NAME;',
    '',
    '    const text = this.#ensureText(resolvedTagName);',
    '    if (!text) {',
    '      return;',
    '    }',
    '',
    '    text.style.fontFamily = `var(--prism-typography-${resolvedVariant}-${resolvedSize}-font-family)`;',
    '    text.style.fontSize = `var(--prism-typography-${resolvedVariant}-${resolvedSize}-font-size)`;',
    '    text.style.fontWeight = `var(--prism-typography-${resolvedVariant}-${resolvedSize}-font-weight)`;',
    '    text.style.letterSpacing = `var(--prism-typography-${resolvedVariant}-${resolvedSize}-letter-spacing)`;',
    '    text.style.lineHeight = `var(--prism-typography-${resolvedVariant}-${resolvedSize}-line-height)`;',
    '  }',
    '}',
    '',
    `export function register${blueprint.className}() {`,
    '  if (typeof customElements === "undefined") {',
    '    return;',
    '  }',
    '',
    `  if (!customElements.get(${JSON.stringify(blueprint.tagName)})) {`,
    `    customElements.define(${JSON.stringify(blueprint.tagName)}, ${blueprint.className});`,
    '  }',
    '}',
    ''
  ].join('\n');
}

function surfaceSource(blueprint: ComponentBlueprint): string {
  const toneAttribute = findAttribute(blueprint, 'tone');
  const elevationAttribute = findAttribute(blueprint, 'elevation');

  const tones = enumValues(toneAttribute);
  const elevations = enumValues(elevationAttribute);

  const defaultTone = enumDefault(toneAttribute);
  const defaultElevation = enumDefault(elevationAttribute);

  const styleHooks = renderStyleHooks(blueprint, [
    { selector: ':host', target: 'host' },
    { selector: '.container', target: 'container' },
    { selector: '.header', target: 'header' },
    { selector: '.body', target: 'body' },
    { selector: '.footer', target: 'footer' }
  ]);

  return [
    ...FILE_HEADER_LINES,
    'const PrismHTMLElement = globalThis.HTMLElement ?? class {};',
    `const SURFACE_TONES = Object.freeze(${renderArray(tones)});`,
    `const SURFACE_ELEVATIONS = Object.freeze(${renderArray(elevations)});`,
    `const DEFAULT_TONE = ${JSON.stringify(defaultTone)};`,
    `const DEFAULT_ELEVATION = ${JSON.stringify(defaultElevation)};`,
    '',
    `export const ${blueprint.className}Slots = Object.freeze(${renderArray(blueprint.slots.map((slot) => slot.name))});`,
    `export const ${blueprint.className}Parts = Object.freeze(${renderArray(blueprint.parts.map((part) => part.name))});`,
    '',
    `export class ${blueprint.className} extends PrismHTMLElement {`,
    `  static tagName = ${JSON.stringify(blueprint.tagName)};`,
    `  static observedAttributes = Object.freeze(${renderArray(
      blueprint.attributes.map((attribute) => attribute.name).sort((left, right) => left.localeCompare(right))
    )});`,
    '',
    '  #container = null;',
    '  #header = null;',
    '  #footer = null;',
    '  #headerSlot = null;',
    '  #footerSlot = null;',
    '',
    '  constructor() {',
    '    super();',
    '    if (typeof this.attachShadow === "function" && !this.shadowRoot) {',
    '      this.attachShadow({ mode: "open" });',
    '    }',
    '  }',
    '',
    '  connectedCallback() {',
    '    this.#render();',
    '    this.#sync();',
    '  }',
    '',
    '  attributeChangedCallback() {',
    '    this.#sync();',
    '  }',
    '',
    '  #render() {',
    '    if (!this.shadowRoot || this.shadowRoot.childNodes.length > 0) {',
    '      return;',
    '    }',
    '',
    '    this.shadowRoot.innerHTML = `',
    '<style>',
    ':host {',
    '  display: block;',
    '}',
    '',
    '.container {',
    '  border: 1px solid transparent;',
    '  box-shadow: 0 calc(var(--prism-surface-elevation-factor, 0) * 1px) calc(var(--prism-surface-elevation-factor, 0) * 4px) rgba(0, 0, 0, 0.24);',
    '  display: grid;',
    '  gap: 1rem;',
    '  padding: 1rem;',
    '  transition: box-shadow 120ms ease, transform 120ms ease;',
    '}',
    '',
    ':host([interactive]) .container {',
    '  cursor: pointer;',
    '}',
    '',
    ':host([interactive]) .container:hover {',
    '  box-shadow: 0 calc(var(--prism-surface-elevation-factor, 0) * 1.5px) calc(var(--prism-surface-elevation-factor, 0) * 5px) rgba(0, 0, 0, 0.24);',
    '  transform: translateY(-1px);',
    '}',
    '',
    '.header,',
    '.footer {',
    '  display: block;',
    '}',
    '',
    '.header[hidden],',
    '.footer[hidden] {',
    '  display: none;',
    '}',
    '',
    '.body {',
    '  display: block;',
    '}',
    '',
    styleHooks,
    '</style>',
    '<section class="container" part="container">',
    '  <header class="header" part="header" hidden><slot name="header"></slot></header>',
    '  <div class="body" part="body"><slot></slot></div>',
    '  <footer class="footer" part="footer" hidden><slot name="footer"></slot></footer>',
    '</section>',
    '`;',
    '',
    '    this.#container = this.shadowRoot.querySelector(".container");',
    '    this.#header = this.shadowRoot.querySelector(".header");',
    '    this.#footer = this.shadowRoot.querySelector(".footer");',
    '    this.#headerSlot = this.shadowRoot.querySelector("slot[name=\\\"header\\\"]");',
    '    this.#footerSlot = this.shadowRoot.querySelector("slot[name=\\\"footer\\\"]");',
    '    this.#headerSlot?.addEventListener("slotchange", () => this.#syncSlotVisibility());',
    '    this.#footerSlot?.addEventListener("slotchange", () => this.#syncSlotVisibility());',
    '  }',
    '',
    '  #syncSlotVisibility() {',
    '    const hasHeader = Boolean(this.#headerSlot?.assignedNodes({ flatten: true }).length);',
    '    const hasFooter = Boolean(this.#footerSlot?.assignedNodes({ flatten: true }).length);',
    '',
    '    this.#header?.toggleAttribute("hidden", !hasHeader);',
    '    this.#footer?.toggleAttribute("hidden", !hasFooter);',
    '  }',
    '',
    '  #sync() {',
    '    const container = this.#container;',
    '    if (!container) {',
    '      return;',
    '    }',
    '',
    '    const tone = this.getAttribute("tone");',
    '    const elevation = this.getAttribute("elevation");',
    '',
    '    const resolvedTone = SURFACE_TONES.includes(tone ?? "") ? tone : DEFAULT_TONE;',
    '    const resolvedElevation = SURFACE_ELEVATIONS.includes(elevation ?? "") ? elevation : DEFAULT_ELEVATION;',
    '',
    '    const toneStyles = {',
    '      default: {',
    '        backgroundColor: "var(--prism-color-surface, #fbf8ff)",',
    '        color: "var(--prism-color-on-surface, #1a1b1f)"',
    '      },',
    '      "container-low": {',
    '        backgroundColor: "var(--prism-color-surface-container-low, #f5f3fa)",',
    '        color: "var(--prism-color-on-surface, #1a1b1f)"',
    '      },',
    '      "container-high": {',
    '        backgroundColor: "var(--prism-color-surface-container-high, #eae7ef)",',
    '        color: "var(--prism-color-on-surface, #1a1b1f)"',
    '      },',
    '      inverse: {',
    '        backgroundColor: "var(--prism-color-inverse-surface, #2f3035)",',
    '        color: "var(--prism-color-inverse-on-surface, #f1eff6)"',
    '      }',
    '    };',
    '',
    '    const toneStyle = toneStyles[resolvedTone];',
    '    container.style.backgroundColor = toneStyle.backgroundColor;',
    '    container.style.color = toneStyle.color;',
    '    container.style.setProperty(',
    '      "--prism-surface-elevation-factor",',
    '      `var(--prism-elevation-${resolvedElevation}, 0)`',
    '    );',
    '',
    '    this.#syncSlotVisibility();',
    '  }',
    '}',
    '',
    `export function register${blueprint.className}() {`,
    '  if (typeof customElements === "undefined") {',
    '    return;',
    '  }',
    '',
    `  if (!customElements.get(${JSON.stringify(blueprint.tagName)})) {`,
    `    customElements.define(${JSON.stringify(blueprint.tagName)}, ${blueprint.className});`,
    '  }',
    '}',
    ''
  ].join('\n');
}

function generateSourceForBlueprint(blueprint: ComponentBlueprint): string {
  switch (blueprint.templateKind) {
    case 'button':
      return buttonSource(blueprint);
    case 'icon-button':
      return iconButtonSource(blueprint);
    case 'typography':
      return typographySource(blueprint);
    case 'surface':
      return surfaceSource(blueprint);
    default:
      throw new Error(`Unsupported template kind "${blueprint.templateKind}".`);
  }
}

export function artifactFileNameForBlueprint(blueprint: ComponentBlueprint): string {
  return `${blueprint.tagName}.component.js`;
}

export function generateComponentArtifact(blueprint: ComponentBlueprint): GeneratedComponentArtifact {
  return {
    componentId: blueprint.componentId,
    tagName: blueprint.tagName,
    artifactFileName: artifactFileNameForBlueprint(blueprint),
    source: generateSourceForBlueprint(blueprint)
  };
}

export function generateComponentArtifacts(
  blueprints: readonly ComponentBlueprint[] = componentBlueprints
): readonly GeneratedComponentArtifact[] {
  return [...blueprints]
    .sort((left, right) => left.componentId.localeCompare(right.componentId))
    .map((blueprint) => generateComponentArtifact(blueprint));
}
