import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

import { componentBlueprints } from '../blueprint/components/index.js';
import {
  GENERATED_COMPONENT_DIRECTORY,
  artifactFileNameForBlueprint,
  generateComponentArtifacts
} from './generate-components.js';

function buildGeneratedIndexSource(): string {
  const blueprints = [...componentBlueprints].sort((left, right) =>
    left.componentId.localeCompare(right.componentId)
  );

  const importLines = blueprints.map((blueprint) => {
    const registerExport = `register${blueprint.className}`;
    return `import { ${blueprint.className}, ${registerExport} } from './${artifactFileNameForBlueprint(
      blueprint
    )}';`;
  });

  const exportBindings = blueprints
    .map((blueprint) => `${blueprint.className}, register${blueprint.className}`)
    .join(',\n  ');

  const registerCalls = blueprints
    .map((blueprint) => `  register${blueprint.className}();`)
    .join('\n');

  const tagNames = blueprints.map((blueprint) => JSON.stringify(blueprint.tagName)).join(', ');

  return [
    '// This file is generated by @prism/ui-core component blueprints.',
    '// Do not edit this file manually.',
    '',
    ...importLines,
    '',
    'export {',
    `  ${exportBindings}`,
    '};',
    '',
    `export const generatedPrismComponentTags = Object.freeze([${tagNames}]);`,
    '',
    'export function registerGeneratedPrismComponents() {',
    registerCalls,
    '}',
    ''
  ].join('\n');
}

export interface GeneratedComponentWriteResult {
  artifactPaths: readonly string[];
  generatedIndexPath: string;
}

export function writeGeneratedComponents(rootDir: string = process.cwd()): GeneratedComponentWriteResult {
  const outputDirectory = path.join(rootDir, GENERATED_COMPONENT_DIRECTORY);
  mkdirSync(outputDirectory, { recursive: true });

  const artifacts = generateComponentArtifacts(componentBlueprints);
  const artifactPaths: string[] = [];

  for (const artifact of artifacts) {
    const outputPath = path.join(outputDirectory, artifact.artifactFileName);
    writeFileSync(outputPath, `${artifact.source}\n`, 'utf8');
    artifactPaths.push(outputPath);
  }

  const generatedIndexPath = path.join(outputDirectory, 'index.js');
  writeFileSync(generatedIndexPath, `${buildGeneratedIndexSource()}\n`, 'utf8');

  return {
    artifactPaths,
    generatedIndexPath
  };
}

const isDirectExecution =
  typeof process.argv[1] === 'string' && import.meta.url === pathToFileURL(process.argv[1]).href;

if (isDirectExecution) {
  const result = writeGeneratedComponents();
  const lines = [
    ...result.artifactPaths.map((artifactPath) => `generated: ${path.relative(process.cwd(), artifactPath)}`),
    `generated: ${path.relative(process.cwd(), result.generatedIndexPath)}`
  ];

  for (const line of lines) {
    console.log(line);
  }
}
